name: dsb_server
description: This package allows you to trivially create a DSB/DSBMobile server.
version: 0.1.2
homepage: https://github.com/Ampless/dsb_server

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  intl: ^0.17.0
  shelf: ^1.2.0

dev_dependencies:
  dsbuntis: ^8.1.0-alpha.0
  lints: ^2.0.0
  test: ^1.18.2
