name: dsb_server
description: This package allows you to trivially create a DSB/DSBMobile server.
version: 0.0.2
homepage: https://github.com/Ampless/dsb_server

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  shelf: ^1.2.0

dev_dependencies:
  dsbuntis: ^6.1.0
  pedantic: ^1.11.0
  test: ^1.18.2
